
name: Weekly Food Menu Update

on:
  schedule:
    - cron: '0 21 * * 0' 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run update script
        run: python update_food.py

      - name: Commit and Push
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add food_menu.jpg
          git commit -m "Auto-update food menu" || exit 0
          git push
